kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
{{- if .Values.host }}
  host: {{ .Values.host }}
{{- end }}
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
